server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1522/ORCLPDB
    username: RIMS_USER_SERVER_DB
    password: Rims#12042026
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/ebecc4e4-d876-48e1-848a-880f6d71bdad/v2.0
          audiences:
            - api://73966a65-f6dc-46f5-b554-8c84028613f8

management:
  endpoints:
    web:
      exposure:
        include: health,info
